### ISSUE TITLE
[FEATURE] - ADD OPTIONAL ABILITY FOR CREATING AN SSH KEY PAIR

### ISSUE THREAD

**Issue by patrick-hermann-sva** [stuttgart-things/aws-ec2-vm#7]
BUUUT IT SHOULD ALSO POSSIBLE TO NOT CREATE A KEY PAIR AND REFRENCE A LOCAL PUB KEY

**Comment by ankitsharma12-ops** [comment]
Since the requirement is to access the VM created this way, with the pub key available on user's local system and referencing the same in the calling module,
I think we don't have to generate a specific key pair this way.
Additionally, I found a way to create the keypair using terraform and to use it to login to EC2 manually.

Please suggest if this issue could be marked as resolved.

**Comment by patrick-hermann-sva** [comment]
its okay for me
